encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:word>", views.query, name="query"),
    path("wiki/", views.search, name="search"),
    path("wiki/newPage/", views.newPage, name="newPage"),
    path("wiki/editpage/", views.editPage, name="editPage"),
    path("wiki/saveEdit/", views.saveEdit, name="saveEdit"),
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render, redirect
from django import forms
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
import random, secrets

from . import util

import markdown2

class NewPageForm(forms.Form):
    title = forms.CharField(label='Title', widget=forms.TextInput(attrs={'placeholder': 'title', 'class': 'sizeform'}))
    content = forms.CharField(label='Description', widget=forms.Textarea(attrs={'placeholder': 'Your description here...'}))

# Creates a function that creates some variables of use along the doc:

def function():
    Entries = util.list_entries() # that will remain has it has been saved...
    entries = util.list_entries() # and this that will be converted to lowercase to be compared to 'word'
    random = secrets.choice(Entries)

    for i in range(len(entries)):
        entries[i] = entries[i].lower()

    # Creates an empty dictionary called capitalize to associated the capitalized word associated to its lowercase version
    capitalize = {}
    for x in range(len(entries)):
        capitalize[Entries[x]] = entries[x]
    
    return [Entries, entries, random, capitalize]

def index(request):
    values = function()
    #print(f"{values[0]}")
    #print(f"{values[2]}")
    return render(request, "encyclopedia/index.html", {
        "entries": values[0],
        "random": values[2]
    })

def query(request, word):
    values = function()
    compare_word = word.lower()
    
    if compare_word in values[1]:
        j = values[1].index(compare_word)
        word = values[0][j]
        #print(f"{word}")
        querySearch = markdown2.markdown(util.get_entry(word))
    else:
        querySearch = None

    return render(request, "encyclopedia/query.html", { 
        "querySearch": querySearch,
        "word": word, # word is capitalized
        "capitalize": values[3],
        "random": values[2]
    })

def search(request):
    values = function()
    if request.method == "POST":
        # get the input 'q' from the user from the form in layout.html
        word = request.POST.get('q')

        if word == '':
            danger = 50
            return HttpResponseRedirect(reverse("encyclopedia:index"), {
                "message": messages.add_message(request, danger, 'Not a valid search.')
            })

        # convert the word into lower case
        compare_word = word.lower()
        
        # use as a check
        # print(f"{capitalize}")

        if compare_word in values[1]:
            j = values[1].index(compare_word)
            word = values[0][j]
            querySearch = markdown2.markdown(util.get_entry(word))
        else:
            querySearch = None

        return render(request, "encyclopedia/search.html", {
            "querySearch": querySearch,
            "Entries": values[0],
            "word": word, 
            "random": values[2],
            "compare_word": compare_word,
            "capitalize": values[3]
        })
    else:
        return redirect("encyclopedia:index")

def newPage(request):
    values = function()
    if request.method == "POST":
        title = request.POST.get('title')
        titleLower = title.lower()
        content = request.POST.get('content')

        danger = 50

        if titleLower in values[1]:
            return render(request, "encyclopedia/newPage.html", {
                "form": NewPageForm,
                "message": messages.add_message(request, danger, 'Error: an entry with the same name already exists. Cannot overrride data. Entry not saved.'),
                "random": values[2]
            })

        else:
            util.save_entry(title,content)
            messages.add_message(request, messages.SUCCESS, 'Entry successfully saved. Thank you for your contribution!!')
            return HttpResponseRedirect(reverse("encyclopedia:query", args=(title,))) 
            # use HttpResponseRedirect instead of redirect to also redirect the flash message.
            # args=(title,) allows to pass the title parameter to the query view to open the new page correctly

    return render(request, "encyclopedia/newPage.html", {
        "form": NewPageForm,
        "random": values[2]
    })

def editPage(request):
    values = function()
    if request.method == "POST":
        title = request.POST.get('word')
        content = util.get_entry(title)

        #print(f"title sent is:{title}")
        return render(request, "encyclopedia/editPage.html", {
            "title": title,
            "content": content,
            "random": values[2]
        })

def saveEdit(request):
    if request.method == "POST":

        title = request.POST.get('title')
        content = request.POST.get('content')

        util.save_entry(title,content)
        messages.add_message(request, messages.SUCCESS, 'Entry successfully saved. Thank you for your contribution!!')
        return HttpResponseRedirect(reverse("encyclopedia:query", args=(title,))) 
        # use HttpResponseRedirect instead of redirect to also redirect the flash message.
        # args=(title,) allows to pass the title parameter to the query view to open the new page correctly

encyclopedia/templates/encyclopedia/editPage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    edit {{title}} page
{% endblock %}

{% block body%}
    <div class="messages" id="messages-list">
        {% if messages %}
            {% for message in messages %}
                {% if message.tags %}
                    <div style="width: 1000px; margin: 0 auto;" class=" alert alert-{{ message.tags }} msg fade show" role="alert">
                        {{ message }}
                    </div>
                {% else %}
                    <div style="width: 1000px; margin: 0 auto;" class=" alert alert-danger msg fade show" role="alert">
                        {{ message }}
                    </div>
                {% endif %}
            {% endfor %}
        {% endif %}
    </div>

    <h1>Edit "{{title}}" entry:</h1>
    </br>

    <div class="size">
        <form action="{% url 'encyclopedia:saveEdit' %}" method="POST">
            {% csrf_token %}
           
                <h3>Title:</h4>
                    <input type='text' disabled='True' value="{{ title }}">
                    <input type ="hidden" value="{{ title }}" id="title" name="title">
                    </br>
                <h3>content:</h3>
                    <textarea name='content'>{{ content }}</textarea>             
            
            <input class="btn btn-primary" type='submit' name="save" value='Save'>
        </form>
    </div>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <div class="messages" id="messages-list">
        {% if messages %}
            {% for message in messages %}
                {% if message.tags %}
                    <div style="width: 1000px; margin: 0 auto;" class="alert alert-{{ message.tags }} msg fade show" role="alert">
                        {{ message }}
                    </div>
                {% else %}
                    <div style="width: 1000px; margin: 0 auto;" class="alert alert-danger msg fade show" role="alert">{{ message }}</div>
                {% endif %}
            {% endfor %}
        {% endif %}
    </div>

    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="wiki/{{ entry }}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles2.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method="POST">
                    {% csrf_token %}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:newPage' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:query' random %}">Random Page</a> <!--passing the arg random to the url-->
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/newPage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    New page
{% endblock %}

{% block body %} 


    <div class="messages" id="messages-list">
        {% if messages %}
            {% for message in messages %}
                {% if message.tags %}
                    <div style="width: 1000px; margin: 0 auto;" class="alert alert-{{ message.tags }} msg fade show" role="alert">
                        {{ message }}
                    </div>
                {% else %}
                    <div style="width: 1000px; margin: 0 auto;" class="alert alert-danger msg fade show" role="alert">{{ message }}</div>
                {% endif %}
            {% endfor %}
        {% endif %}
    </div>

    <h1>Create a new entry:</h1> 
    <br>
    <div class="size">
        <form action="{% url 'encyclopedia:newPage' %}" method="POST">
            {% csrf_token %}
            <div class="grid">
                {% for field in form %} <!-- To iterate through the form NewPageForm-->
                    <h3>{{ field.label_tag }}</h3>
                        <span>{{ field }}</span>              
                {% endfor %}
                <input class="button" type="submit" name="save" value="Save">
            </div>
        </form>
    </div>
{% endblock %}
    

encyclopedia/templates/encyclopedia/query.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Wiki: {{word}}
{% endblock%}

{% block body %}
    <div class="messages" id="messages-list">
        {% if messages %}
            {% for message in messages %}
                {% if message.tags %}
                    <div style="width: 1000px; margin: 0 auto;" class="alert alert-{{ message.tags }} msg fade show" role="alert">
                        {{ message }}
                    </div>
                {% else %}
                    <div style="width: 1000px; margin: 0 auto;" class="alert alert-danger msg fade show" role="alert">{{ message }}</div>
                {% endif %}
            {% endfor %}
        {% endif %}
    </div>

        {% if not querySearch %}
            <form action="{% url 'encyclopedia:newPage' %}">
                {% csrf_token %}
                <h1>Page not found... </h1><br><h2>Sorry, it seems that there is no wikipage yet for the word "{{ word }}" that you are looking for. 
                    Think about creating one!</h2>
                </br>
                    <button style="margin-top: 15px;"type="submit" class="btn btn-primary">Create a new entry</button>
            </form>
        {% else %}
            <form action="{% url 'encyclopedia:editPage' %}" method="POST">
                {% csrf_token %}
                {{ querySearch|safe }}
                </br>
                <input type ="hidden" value="{{ word }}" id="word" name="word">
                <button style="margin-top: 15px;"type="submit" class="btn btn-primary">Edit</button>
            </form>
        {% endif %}

{% endblock%}

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title%}
    {{ word }}
{% endblock %}

{% block body %}  
    {% if querySearch %}
        {{ querySearch|safe }}
        </br>
        <form action="{% url 'encyclopedia:editPage' %}"" method="POST">
            {% csrf_token %}
            <input type ="hidden" value="{{ word }}" id="word" name="word">
            <button style="margin-top: 15px;"type="submit" class="btn btn-primary">Edit</button>
        </form>
    {% else %}
    <h1>May be you meant one of the entries below:</h1>
        <ul>

            {% for key, value in capitalize.items %}
                {% if compare_word in value %}
                    <li><a href="{{ key }}">{{ key }}</a></li>
                {% endif %}
            {% endfor %}
        </ul>

        <span>Or create your own entry</span>
        <form action="{% url 'encyclopedia:newPage' %}"" method="GET">
            {% csrf_token %}
            <input type ="hidden" value="{{ word }}" id="word" name="word">
            <button style="margin-top: 15px;"type="submit" class="btn btn-primary">Create new entry</button>
        </form>
    {% endif %}

{% endblock %}